FROM grafana/grafana:7.5.10-ubuntu

COPY LICENSE                          /linkerd/LICENSE
COPY grafana/dashboards               /var/lib/grafana/dashboards
COPY grafana/dashboards/top-line.json /usr/share/grafana/public/dashboards/home.json
